version = 0.1
[development.deploy.parameters]
stack_name = "resumeSAM"
resolve_s3 = true
s3_prefix = "resumeSAM"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
