AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Lambda function to update and get visitor count'

Parameters:
  MyIAMRoleArn:
    Type: String
    Description: "ARN of the IAM role for the Lambda function"
  MyCodeSignArn:
    Type: String
    Description: "ARN of the Code signer for the Lambda function"

Resources:
  MySignedFunctionCodeSigningConfig:
    Type: AWS::Lambda::CodeSigningConfig
    Properties:
      Description: Code Signing for MyFunction
      AllowedPublishers: 
        SigningProfileVersionArns:
          - !Ref MyCodeSignArn
      CodeSigningPolicies:
        UntrustedArtifactOnDeployment: Enforce

  VisitorCountFunction2:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      FunctionName: VisitorCountFunction2
      CodeSigningConfigArn: !Ref MySignedFunctionCodeSigningConfig
      Timeout: 10
      MemorySize: 128
      Role: !Ref MyIAMRoleArn
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: OPTIONS
