name: Deploy Stack to Production

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.5.4

    - name: Set up Python
      uses: actions/setup-python@v2.7.2
      with:
        python-version: 3.8  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 

    - name: Run tests
      run: |
        python -m unittest discover

    - name: Deploy Stack
      run: |
        sam build
        sam deploy --stack-name resumeSAM --region eu-north-1 --capabilities CAPABILITY_IAM --s3-bucket ${{ secrets.AWS_DEPLOY_BUCKET }} --parameter-overrides Key1=Value1 Key2=Value2
      
