name: Deploy to AWS

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 

    - name: Run tests
      run: |
        python -m unittest discover

    - name: Deploy to AWS
      uses: aws-actions/aws-sam-deploy@v1
      with:
        stack-name: resumeSAM  
        region: eu-north-1  
        capabilities: CAPABILITY_IAM
