name: "Deploy the SAM Stack to Production"
on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Enable debug output
      env:
        ACTIONS_STEP_DEBUG: true

    - name: Checkout code
      uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 

    - name: Run tests
      run: |
        python -m unittest discover

    - name: Deploy SAM Stack
      uses: abdulxs/aws-sam-deploy-action@v1.3.0
      env:
        TEMPLATE: 'template.yaml'
        AWS_STACK_NAME: resumeSAM
        AWS_REGION: 'eu-north-1'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEPLOY_BUCKET: ${{ secrets.AWS_DEPLOY_BUCKET }}
        capabilities: CAPABILITY_IAM
